# Generated by Django 3.1.6 on 2021-02-03 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='None', max_length=30)),
                ('last_name', models.CharField(default='None', max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('scientific_rate', models.IntegerField(default=0)),
                ('contribution_rate', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teach_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=1000, null=True)),
                ('expectations', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(null=True)),
                ('generalـprocess', models.CharField(max_length=3000)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cusername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mhbank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('verification_status', models.CharField(max_length=50)),
                ('verification_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('events', models.ManyToManyField(blank=True, to='mhbank.Event')),
                ('question_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.account')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mhbank.source')),
                ('sub_tags', models.ManyToManyField(blank=True, to='mhbank.Sub_tag')),
                ('tags', models.ManyToManyField(blank=True, to='mhbank.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mhbank.problem'),
        ),
    ]
